apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
name: dumbkv-servicemonitor
labels:
release: prometheus
spec:
selector:
matchLabels:
app: dumbkv
endpoints:
- port: http
path: /metrics
interval: 30s
