name: Test with SQLite

on:
pull_request:

jobs:
test:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3
- uses: actions/setup-python@v4
with:
python-version: '3.12'

- name: Install uv
run: pip install uv

- name: Install dependencies
run: uv sync


- name: Run tests
run: uv run python -m pytest -v
